{% set name = "exo_puppies" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exo_puppies-{{ version }}.tar.gz
  sha256: 672d6cfcb9bc6f6380cc1c4dd6984fe02ee90a4ae026766722583f4f77ea759d

build:
  entry_points:
    - pup = puppies.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2
  skip: true  # [win]
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
  run:
    - astropy-base >=3.1
    - matplotlib-base >=1.3.1
    - mc3 >=3.0.6
    - python
    - scipy >=1.4.1

test:
  imports:
    - puppies
  commands:
    - pip check
    - pup --help
  requires:
    - pip

about:
  home: https://github.com/pcubillos/puppies
  summary: The Public Photometry Pipeline for Exoplanets
  license: GPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/puppies
  doc_url: https://puppies.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - pcubillos
